name: Package

on:
  push:
    branches: [main]
    paths-ignore: [dist/**]

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Nix
        uses: nixbuild/nix-quick-install-action@v16
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: Install dependencies
        run: nix develop -i -c npm ci

      - name: Clean old distribution
        run: nix develop -i -c npm run clean
      - name: Build & Package
        run: nix develop -i -c npm run build

      - name: Get Git commit hash
        id: get-commit
        run: |
          echo "::set-output name=hash::$(git rev-list --max-count=1 --abbrev-commit HEAD)"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: dist-update
          assignees: jessestricker
          commit-message: "chore: update distribution to ${{ steps.get-commit.outputs.hash }}"
          title: "chore: update distribution to ${{ steps.get-commit.outputs.hash }}"
          body: |
            This pull request updates the contents of the distribution folder
            to reflect the latest packaged sources.
